init.file=empty_init.txt

# PostgreSQL remote database for production
spring.datasource.url=jdbc:postgresql://35.192.79.142:5432/postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.username=postgres
spring.datasource.password=Pass_1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=false
