spring.application.name=ticket
spring.profiles.active=dev
jwt.secret=myUltraSecretKeyForJWTSigningThatIsAtLeast32CharactersLong
spring.security.user.name=user
spring.security.user.password=409e2525-e72e-4d5c-bedd-2b9d7af70449