spring.application.name=ticket
spring.profiles.active=prod
spring.security.user.name=user
jwt.secret=myUltraSecretKeyForJWTSigningThatIsAtLeast32CharactersLong
spring.security.user.password=409e2525-e72e-4d5c-bedd-2b9d7af70449

gateway.api.url=https://damp-lynna-wsep-1984852e.koyeb.app/
admin.id=admin-1
admin.name=Admin
admin.email=admin@gmail.com
admin.password=admin123


spring.security.headers.frame-options.config=sameorigin
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console 
