spring.application.name=ticket
spring.profiles.active=dev
jwt.secret=myUltraSecretKeyForJWTSigningThatIsAtLeast32CharactersLong
spring.security.user.name=user
spring.security.user.password=409e2525-e72e-4d5c-bedd-2b9d7af70449

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:ticketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.security.headers.frame-options.config=sameorigin